apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: pythonapp
    #this name should come from template.metaddata.label
  ports:
    - port: 80
      targetPort: 8000
      nodePort: 30007